package com.example.demo.dto;

public class QosDataKeyDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.id
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.source_name
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.des_name
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String desName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.timestamp
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.id
     *
     * @return the value of packet_loss_20210828.id
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.id
     *
     * @param id the value for packet_loss_20210828.id
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.source_name
     *
     * @return the value of packet_loss_20210828.source_name
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.source_name
     *
     * @param sourceName the value for packet_loss_20210828.source_name
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.des_name
     *
     * @return the value of packet_loss_20210828.des_name
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getDesName() {
        return desName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.des_name
     *
     * @param desName the value for packet_loss_20210828.des_name
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setDesName(String desName) {
        this.desName = desName == null ? null : desName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.timestamp
     *
     * @return the value of packet_loss_20210828.timestamp
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.timestamp
     *
     * @param timestamp the value for packet_loss_20210828.timestamp
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }
}