package com.example.demo.dto;

import lombok.ToString;

@ToString
public class QosDataDO extends QosDataKeyDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.source_ip
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String sourceIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.des_ip
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String desIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.interval1
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String interval1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.num
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.p_interval
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String pInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.p_num
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String pNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.step
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.protocol
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.packet_size
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String packetSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.value
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.p_seq
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String pSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet_loss_20210828.ts
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    private String ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.source_ip
     *
     * @return the value of packet_loss_20210828.source_ip
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getSourceIp() {
        return sourceIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.source_ip
     *
     * @param sourceIp the value for packet_loss_20210828.source_ip
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp == null ? null : sourceIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.des_ip
     *
     * @return the value of packet_loss_20210828.des_ip
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getDesIp() {
        return desIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.des_ip
     *
     * @param desIp the value for packet_loss_20210828.des_ip
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setDesIp(String desIp) {
        this.desIp = desIp == null ? null : desIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.interval1
     *
     * @return the value of packet_loss_20210828.interval1
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getInterval1() {
        return interval1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.interval1
     *
     * @param interval1 the value for packet_loss_20210828.interval1
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setInterval1(String interval1) {
        this.interval1 = interval1 == null ? null : interval1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.num
     *
     * @return the value of packet_loss_20210828.num
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.num
     *
     * @param num the value for packet_loss_20210828.num
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.p_interval
     *
     * @return the value of packet_loss_20210828.p_interval
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getpInterval() {
        return pInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.p_interval
     *
     * @param pInterval the value for packet_loss_20210828.p_interval
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setpInterval(String pInterval) {
        this.pInterval = pInterval == null ? null : pInterval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.p_num
     *
     * @return the value of packet_loss_20210828.p_num
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getpNum() {
        return pNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.p_num
     *
     * @param pNum the value for packet_loss_20210828.p_num
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setpNum(String pNum) {
        this.pNum = pNum == null ? null : pNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.step
     *
     * @return the value of packet_loss_20210828.step
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.step
     *
     * @param step the value for packet_loss_20210828.step
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.protocol
     *
     * @return the value of packet_loss_20210828.protocol
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.protocol
     *
     * @param protocol the value for packet_loss_20210828.protocol
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.packet_size
     *
     * @return the value of packet_loss_20210828.packet_size
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getPacketSize() {
        return packetSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.packet_size
     *
     * @param packetSize the value for packet_loss_20210828.packet_size
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setPacketSize(String packetSize) {
        this.packetSize = packetSize == null ? null : packetSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.value
     *
     * @return the value of packet_loss_20210828.value
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.value
     *
     * @param value the value for packet_loss_20210828.value
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.p_seq
     *
     * @return the value of packet_loss_20210828.p_seq
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getpSeq() {
        return pSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.p_seq
     *
     * @param pSeq the value for packet_loss_20210828.p_seq
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setpSeq(String pSeq) {
        this.pSeq = pSeq == null ? null : pSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet_loss_20210828.ts
     *
     * @return the value of packet_loss_20210828.ts
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet_loss_20210828.ts
     *
     * @param ts the value for packet_loss_20210828.ts
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setTs(String ts) {
        this.ts = ts == null ? null : ts.trim();
    }
}