package com.example.demo.dto;

import java.util.ArrayList;
import java.util.List;

public class QosDataExampleDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public QosDataExampleDO() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourceNameIsNull() {
            addCriterion("source_name is null");
            return (Criteria) this;
        }

        public Criteria andSourceNameIsNotNull() {
            addCriterion("source_name is not null");
            return (Criteria) this;
        }

        public Criteria andSourceNameEqualTo(String value) {
            addCriterion("source_name =", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameNotEqualTo(String value) {
            addCriterion("source_name <>", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameGreaterThan(String value) {
            addCriterion("source_name >", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("source_name >=", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameLessThan(String value) {
            addCriterion("source_name <", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameLessThanOrEqualTo(String value) {
            addCriterion("source_name <=", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameLike(String value) {
            addCriterion("source_name like", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameNotLike(String value) {
            addCriterion("source_name not like", value, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameIn(List<String> values) {
            addCriterion("source_name in", values, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameNotIn(List<String> values) {
            addCriterion("source_name not in", values, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameBetween(String value1, String value2) {
            addCriterion("source_name between", value1, value2, "sourceName");
            return (Criteria) this;
        }

        public Criteria andSourceNameNotBetween(String value1, String value2) {
            addCriterion("source_name not between", value1, value2, "sourceName");
            return (Criteria) this;
        }

        public Criteria andDesNameIsNull() {
            addCriterion("des_name is null");
            return (Criteria) this;
        }

        public Criteria andDesNameIsNotNull() {
            addCriterion("des_name is not null");
            return (Criteria) this;
        }

        public Criteria andDesNameEqualTo(String value) {
            addCriterion("des_name =", value, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameNotEqualTo(String value) {
            addCriterion("des_name <>", value, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameGreaterThan(String value) {
            addCriterion("des_name >", value, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameGreaterThanOrEqualTo(String value) {
            addCriterion("des_name >=", value, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameLessThan(String value) {
            addCriterion("des_name <", value, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameLessThanOrEqualTo(String value) {
            addCriterion("des_name <=", value, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameLike(String value) {
            addCriterion("des_name like", value, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameNotLike(String value) {
            addCriterion("des_name not like", value, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameIn(List<String> values) {
            addCriterion("des_name in", values, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameNotIn(List<String> values) {
            addCriterion("des_name not in", values, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameBetween(String value1, String value2) {
            addCriterion("des_name between", value1, value2, "desName");
            return (Criteria) this;
        }

        public Criteria andDesNameNotBetween(String value1, String value2) {
            addCriterion("des_name not between", value1, value2, "desName");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(String value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(String value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(String value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(String value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(String value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(String value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLike(String value) {
            addCriterion("timestamp like", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotLike(String value) {
            addCriterion("timestamp not like", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<String> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<String> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(String value1, String value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(String value1, String value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andSourceIpIsNull() {
            addCriterion("source_ip is null");
            return (Criteria) this;
        }

        public Criteria andSourceIpIsNotNull() {
            addCriterion("source_ip is not null");
            return (Criteria) this;
        }

        public Criteria andSourceIpEqualTo(String value) {
            addCriterion("source_ip =", value, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpNotEqualTo(String value) {
            addCriterion("source_ip <>", value, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpGreaterThan(String value) {
            addCriterion("source_ip >", value, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpGreaterThanOrEqualTo(String value) {
            addCriterion("source_ip >=", value, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpLessThan(String value) {
            addCriterion("source_ip <", value, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpLessThanOrEqualTo(String value) {
            addCriterion("source_ip <=", value, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpLike(String value) {
            addCriterion("source_ip like", value, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpNotLike(String value) {
            addCriterion("source_ip not like", value, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpIn(List<String> values) {
            addCriterion("source_ip in", values, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpNotIn(List<String> values) {
            addCriterion("source_ip not in", values, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpBetween(String value1, String value2) {
            addCriterion("source_ip between", value1, value2, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andSourceIpNotBetween(String value1, String value2) {
            addCriterion("source_ip not between", value1, value2, "sourceIp");
            return (Criteria) this;
        }

        public Criteria andDesIpIsNull() {
            addCriterion("des_ip is null");
            return (Criteria) this;
        }

        public Criteria andDesIpIsNotNull() {
            addCriterion("des_ip is not null");
            return (Criteria) this;
        }

        public Criteria andDesIpEqualTo(String value) {
            addCriterion("des_ip =", value, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpNotEqualTo(String value) {
            addCriterion("des_ip <>", value, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpGreaterThan(String value) {
            addCriterion("des_ip >", value, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpGreaterThanOrEqualTo(String value) {
            addCriterion("des_ip >=", value, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpLessThan(String value) {
            addCriterion("des_ip <", value, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpLessThanOrEqualTo(String value) {
            addCriterion("des_ip <=", value, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpLike(String value) {
            addCriterion("des_ip like", value, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpNotLike(String value) {
            addCriterion("des_ip not like", value, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpIn(List<String> values) {
            addCriterion("des_ip in", values, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpNotIn(List<String> values) {
            addCriterion("des_ip not in", values, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpBetween(String value1, String value2) {
            addCriterion("des_ip between", value1, value2, "desIp");
            return (Criteria) this;
        }

        public Criteria andDesIpNotBetween(String value1, String value2) {
            addCriterion("des_ip not between", value1, value2, "desIp");
            return (Criteria) this;
        }

        public Criteria andInterval1IsNull() {
            addCriterion("interval1 is null");
            return (Criteria) this;
        }

        public Criteria andInterval1IsNotNull() {
            addCriterion("interval1 is not null");
            return (Criteria) this;
        }

        public Criteria andInterval1EqualTo(String value) {
            addCriterion("interval1 =", value, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1NotEqualTo(String value) {
            addCriterion("interval1 <>", value, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1GreaterThan(String value) {
            addCriterion("interval1 >", value, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1GreaterThanOrEqualTo(String value) {
            addCriterion("interval1 >=", value, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1LessThan(String value) {
            addCriterion("interval1 <", value, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1LessThanOrEqualTo(String value) {
            addCriterion("interval1 <=", value, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1Like(String value) {
            addCriterion("interval1 like", value, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1NotLike(String value) {
            addCriterion("interval1 not like", value, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1In(List<String> values) {
            addCriterion("interval1 in", values, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1NotIn(List<String> values) {
            addCriterion("interval1 not in", values, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1Between(String value1, String value2) {
            addCriterion("interval1 between", value1, value2, "interval1");
            return (Criteria) this;
        }

        public Criteria andInterval1NotBetween(String value1, String value2) {
            addCriterion("interval1 not between", value1, value2, "interval1");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andPIntervalIsNull() {
            addCriterion("p_interval is null");
            return (Criteria) this;
        }

        public Criteria andPIntervalIsNotNull() {
            addCriterion("p_interval is not null");
            return (Criteria) this;
        }

        public Criteria andPIntervalEqualTo(String value) {
            addCriterion("p_interval =", value, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalNotEqualTo(String value) {
            addCriterion("p_interval <>", value, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalGreaterThan(String value) {
            addCriterion("p_interval >", value, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalGreaterThanOrEqualTo(String value) {
            addCriterion("p_interval >=", value, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalLessThan(String value) {
            addCriterion("p_interval <", value, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalLessThanOrEqualTo(String value) {
            addCriterion("p_interval <=", value, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalLike(String value) {
            addCriterion("p_interval like", value, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalNotLike(String value) {
            addCriterion("p_interval not like", value, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalIn(List<String> values) {
            addCriterion("p_interval in", values, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalNotIn(List<String> values) {
            addCriterion("p_interval not in", values, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalBetween(String value1, String value2) {
            addCriterion("p_interval between", value1, value2, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPIntervalNotBetween(String value1, String value2) {
            addCriterion("p_interval not between", value1, value2, "pInterval");
            return (Criteria) this;
        }

        public Criteria andPNumIsNull() {
            addCriterion("p_num is null");
            return (Criteria) this;
        }

        public Criteria andPNumIsNotNull() {
            addCriterion("p_num is not null");
            return (Criteria) this;
        }

        public Criteria andPNumEqualTo(String value) {
            addCriterion("p_num =", value, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumNotEqualTo(String value) {
            addCriterion("p_num <>", value, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumGreaterThan(String value) {
            addCriterion("p_num >", value, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumGreaterThanOrEqualTo(String value) {
            addCriterion("p_num >=", value, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumLessThan(String value) {
            addCriterion("p_num <", value, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumLessThanOrEqualTo(String value) {
            addCriterion("p_num <=", value, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumLike(String value) {
            addCriterion("p_num like", value, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumNotLike(String value) {
            addCriterion("p_num not like", value, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumIn(List<String> values) {
            addCriterion("p_num in", values, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumNotIn(List<String> values) {
            addCriterion("p_num not in", values, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumBetween(String value1, String value2) {
            addCriterion("p_num between", value1, value2, "pNum");
            return (Criteria) this;
        }

        public Criteria andPNumNotBetween(String value1, String value2) {
            addCriterion("p_num not between", value1, value2, "pNum");
            return (Criteria) this;
        }

        public Criteria andStepIsNull() {
            addCriterion("step is null");
            return (Criteria) this;
        }

        public Criteria andStepIsNotNull() {
            addCriterion("step is not null");
            return (Criteria) this;
        }

        public Criteria andStepEqualTo(String value) {
            addCriterion("step =", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotEqualTo(String value) {
            addCriterion("step <>", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThan(String value) {
            addCriterion("step >", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThanOrEqualTo(String value) {
            addCriterion("step >=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThan(String value) {
            addCriterion("step <", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThanOrEqualTo(String value) {
            addCriterion("step <=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLike(String value) {
            addCriterion("step like", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotLike(String value) {
            addCriterion("step not like", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepIn(List<String> values) {
            addCriterion("step in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotIn(List<String> values) {
            addCriterion("step not in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepBetween(String value1, String value2) {
            addCriterion("step between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotBetween(String value1, String value2) {
            addCriterion("step not between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andProtocolIsNull() {
            addCriterion("protocol is null");
            return (Criteria) this;
        }

        public Criteria andProtocolIsNotNull() {
            addCriterion("protocol is not null");
            return (Criteria) this;
        }

        public Criteria andProtocolEqualTo(String value) {
            addCriterion("protocol =", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotEqualTo(String value) {
            addCriterion("protocol <>", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolGreaterThan(String value) {
            addCriterion("protocol >", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolGreaterThanOrEqualTo(String value) {
            addCriterion("protocol >=", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLessThan(String value) {
            addCriterion("protocol <", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLessThanOrEqualTo(String value) {
            addCriterion("protocol <=", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLike(String value) {
            addCriterion("protocol like", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotLike(String value) {
            addCriterion("protocol not like", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolIn(List<String> values) {
            addCriterion("protocol in", values, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotIn(List<String> values) {
            addCriterion("protocol not in", values, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolBetween(String value1, String value2) {
            addCriterion("protocol between", value1, value2, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotBetween(String value1, String value2) {
            addCriterion("protocol not between", value1, value2, "protocol");
            return (Criteria) this;
        }

        public Criteria andPacketSizeIsNull() {
            addCriterion("packet_size is null");
            return (Criteria) this;
        }

        public Criteria andPacketSizeIsNotNull() {
            addCriterion("packet_size is not null");
            return (Criteria) this;
        }

        public Criteria andPacketSizeEqualTo(String value) {
            addCriterion("packet_size =", value, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeNotEqualTo(String value) {
            addCriterion("packet_size <>", value, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeGreaterThan(String value) {
            addCriterion("packet_size >", value, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeGreaterThanOrEqualTo(String value) {
            addCriterion("packet_size >=", value, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeLessThan(String value) {
            addCriterion("packet_size <", value, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeLessThanOrEqualTo(String value) {
            addCriterion("packet_size <=", value, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeLike(String value) {
            addCriterion("packet_size like", value, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeNotLike(String value) {
            addCriterion("packet_size not like", value, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeIn(List<String> values) {
            addCriterion("packet_size in", values, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeNotIn(List<String> values) {
            addCriterion("packet_size not in", values, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeBetween(String value1, String value2) {
            addCriterion("packet_size between", value1, value2, "packetSize");
            return (Criteria) this;
        }

        public Criteria andPacketSizeNotBetween(String value1, String value2) {
            addCriterion("packet_size not between", value1, value2, "packetSize");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("value is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("value is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(String value) {
            addCriterion("value =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(String value) {
            addCriterion("value <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(String value) {
            addCriterion("value >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(String value) {
            addCriterion("value >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(String value) {
            addCriterion("value <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(String value) {
            addCriterion("value <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLike(String value) {
            addCriterion("value like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotLike(String value) {
            addCriterion("value not like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<String> values) {
            addCriterion("value in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<String> values) {
            addCriterion("value not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(String value1, String value2) {
            addCriterion("value between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(String value1, String value2) {
            addCriterion("value not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andPSeqIsNull() {
            addCriterion("p_seq is null");
            return (Criteria) this;
        }

        public Criteria andPSeqIsNotNull() {
            addCriterion("p_seq is not null");
            return (Criteria) this;
        }

        public Criteria andPSeqEqualTo(String value) {
            addCriterion("p_seq =", value, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqNotEqualTo(String value) {
            addCriterion("p_seq <>", value, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqGreaterThan(String value) {
            addCriterion("p_seq >", value, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqGreaterThanOrEqualTo(String value) {
            addCriterion("p_seq >=", value, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqLessThan(String value) {
            addCriterion("p_seq <", value, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqLessThanOrEqualTo(String value) {
            addCriterion("p_seq <=", value, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqLike(String value) {
            addCriterion("p_seq like", value, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqNotLike(String value) {
            addCriterion("p_seq not like", value, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqIn(List<String> values) {
            addCriterion("p_seq in", values, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqNotIn(List<String> values) {
            addCriterion("p_seq not in", values, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqBetween(String value1, String value2) {
            addCriterion("p_seq between", value1, value2, "pSeq");
            return (Criteria) this;
        }

        public Criteria andPSeqNotBetween(String value1, String value2) {
            addCriterion("p_seq not between", value1, value2, "pSeq");
            return (Criteria) this;
        }

        public Criteria andTsIsNull() {
            addCriterion("ts is null");
            return (Criteria) this;
        }

        public Criteria andTsIsNotNull() {
            addCriterion("ts is not null");
            return (Criteria) this;
        }

        public Criteria andTsEqualTo(String value) {
            addCriterion("ts =", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotEqualTo(String value) {
            addCriterion("ts <>", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThan(String value) {
            addCriterion("ts >", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThanOrEqualTo(String value) {
            addCriterion("ts >=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThan(String value) {
            addCriterion("ts <", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThanOrEqualTo(String value) {
            addCriterion("ts <=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLike(String value) {
            addCriterion("ts like", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotLike(String value) {
            addCriterion("ts not like", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsIn(List<String> values) {
            addCriterion("ts in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotIn(List<String> values) {
            addCriterion("ts not in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsBetween(String value1, String value2) {
            addCriterion("ts between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotBetween(String value1, String value2) {
            addCriterion("ts not between", value1, value2, "ts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 02 15:03:18 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}