package com.example.demo.mapper;

import com.example.demo.dto.*;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface QosDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    int deleteByPrimaryKey(QosDataKeyDO key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    int insert(QosDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    int insertSelective(QosDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    List<QosDataDO> selectByExample(QosDataExampleDO example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    QosDataDO selectByPrimaryKey(QosDataKeyDO key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    int updateByPrimaryKeySelective(QosDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet_loss_20210828
     *
     * @mbggenerated Thu Dec 02 15:03:18 CST 2021
     */
    int updateByPrimaryKey(QosDataDO record);

    List<QosCoreFieldDO> selectByExample2(WithTableNameAndCriteriaParam param);

    List<QosCoreFieldDO> selectBySrcAndDesName(WithTableNameAndCriteriaParam param);
}